Feature implement persistence
yxyx-github/hwr-oop-group-4-todo pull request #55
Opened 2023-05-08 06:17 UTC by yxyx-github

This is the first part. Only save into a json file implemented. Load implementation will be implemented in the future.

2023-05-08 10:12 UTC, vreoio commented
Shouldn't the dependencies be added to the README?

2023-05-08 17:14 UTC, termitehuegel requested changes
I have found some minor mistakes and have added a few recommendations in other places.

2023-05-08 17:14 UTC, termitehuegel commented on src/test/java/hwr/oop/group4/todo/persistence/PersistedTodoListTest.java
> +        // System.out.println(persistedTodoList.toString());
Do not comment out code

2023-05-08 17:14 UTC, termitehuegel commented on src/test/java/hwr/oop/group4/todo/persistence/FileAdapterTest.java
> +        FileAdapter fileAdapter = new FileAdapter(file);
Try to work with the Interface.

2023-05-08 17:44 UTC, yxyx-github commented on src/main/java/hwr/oop/group4/todo/persistence/Persisted.java
> +    String toString();
What do you think about ```exportAsString```?

2023-05-08 17:51 UTC, yxyx-github commented on pom.xml
> +            <version>${mockito.version}</version>
Why should I use it for the new dependencies while we don't use it for the rest? (Also I'm not familar with this.)

2023-05-09 06:25 UTC, termitehuegel approved these changes

2023-05-09 06:25 UTC, merged