Feature implement persistence
yxyx-github/hwr-oop-group-4-todo pull request #72
Opened 2023-05-09 11:11 UTC by yxyx-github

Issue #65

2023-05-09 17:39 UTC, termitehuegel requested changes

2023-05-09 17:39 UTC, termitehuegel commented on src/main/java/hwr/oop/group4/todo/persistence/FileAdapter.java
> +            Scanner scanner = new Scanner(file);
scanner should be closed => use try with resource

2023-05-09 17:39 UTC, termitehuegel commented on src/main/java/hwr/oop/group4/todo/persistence/PersistableTodoList.java
> +
fill with code or add a comment

2023-05-09 17:56 UTC, yxyx-github commented
The second part (load from file and convert) still work in progress. I will let you know when I'm ready.

2023-05-10 05:00 UTC, yxyx-github commented
~~The second part (load from file and convert) still work in progress. I will let you know when I'm ready.~~

I should have taken a different branch for additional stuff that do not address this issue.

2023-05-30 12:09 UTC, termitehuegel approved these changes
approved for consultation

2023-05-30 13:24 UTC, merged