Feature projects to tasks
yxyx-github/hwr-oop-group-4-todo pull request #85
Opened 2023-05-23 07:39 UTC by termitehuegel

2023-05-23 08:43 UTC, vreoio requested changes

2023-05-30 12:19 UTC, termitehuegel commented on src/main/java/hwr/oop/group4/todo/ui/ProjectUi.java
> +        taskUi.menu(projects.get(id), List.of("projects", String.valueOf(id)));
all references are made by id (edit, remove, etc.) because names can overlap.
It be the same for displaying the tasks

2023-05-30 12:51 UTC, vreoio commented on src/main/java/hwr/oop/group4/todo/ui/ProjectUi.java
> +        taskUi.menu(projects.get(id), List.of("projects", String.valueOf(id)));
Ok, true. To to open the task menu the user already needs to know the id, so my idea is unnecessary.

2023-05-30 12:52 UTC, vreoio approved these changes

2023-05-30 12:54 UTC, merged